### ISSUE TITLE
What is your difference with Grounding-SAM?

### ISSUE THREAD

**Issue by LinghaoChan** [geekyutao/Inpaint-Anything#1]
I am curious about your difference with Grounding-SAM.

**Comment by geekyutao** [comment]
> I am curious about your difference with Grounding-SAM.

Hi, here are the differences.
- GroundedSAM uses grounding models to locate objects and obtain box prompts for SAM, while ours is based on point prompts which are clicked by users, more user-friendly and convenient.
- Our model supports object removal and background changing.
- Besides, we make some practice/modifications tailored for image inpainting scenarios such as dilating masks.

**Comment by LinghaoChan** [comment]
@geekyutao GroundedSAM also support the image inpainting. Right?
