### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by AnukritiSinghh** [geekyutao/Inpaint-Anything#10]
is there a hugging face for this?

**Comment by geekyutao** [comment]
> is there a hugging face for this?

Thx. HuggingFace page will be supported shortly.

**Comment by geekyutao** [comment]
@AnukritiSinghh Our website is available now! Check out the interface from [here](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything).

**Comment by emlcpfx** [comment]
@geekyutao You probably know this, but the website is down.

**Comment by geekyutao** [comment]
> @geekyutao You probably know this, but the website is down.

Working on this. Please kindly wait for a few minutes.

**Comment by geekyutao** [comment]
I close this issue as completed.
