### ISSUE TITLE
How to get accurate  point_coords？

### ISSUE THREAD

**Issue by AIBUWAN** [geekyutao/Inpaint-Anything#12]
想用自己的数据进行inpaint，怎么获取要去掉物体--point_coords这个参数？

运行的时候没有SAM那个交互式的界面，这是正常的吗？怎么开启SAM交互式界面获得--point_coords？

谢谢！！

**Comment by RysonFeng** [comment]
你好，目前交互界面正在开发，会尽量在这周以内上线一个简单版本。
目前想找到准确的 point_coords 一般靠目测+多次运行尝试，或者运行以下python代码进行本地交互来获取目标点（可能对windows系统用户来说比较不方便）：
```python
import cv2

def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print("Point coordinates ({}, {})".format(x, y))
        
img = cv2.imread("/Users/torres/Desktop/FA_demo/FA8_paints.jpeg")
cv2.imshow("Image", img)
cv2.setMouseCallback("Image", click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by geekyutao** [comment]
> 想用自己的数据进行inpaint，怎么获取要去掉物体--point_coords这个参数？
> 
> 运行的时候没有SAM那个交互式的界面，这是正常的吗？怎么开启SAM交互式界面获得--point_coords？
> 
> 谢谢！！

The function that can get click coordinates is added to ./utils/.
