### ISSUE TITLE
ValueError: mutable default not allowed 

### ISSUE THREAD

**Issue by alireza18878** [geekyutao/Inpaint-Anything#125]
Hi all,

I have installed Remove Anything environment (as mentioned [here](https://github.com/geekyutao/Inpaint-Anything)) and my Python version is 3.10, which is higher than the required Python version of 3.8.

However, when I run the following script:

`bash script/remove_anything.sh
`

I get this error:

`File "/Users/alirezaaminian/anaconda3/lib/python3.11/site-packages/hydra/conf/__init__.py", line 70, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/Users/alirezaaminian/anaconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory`

Python does not accept mutable values as keys in dictionaries, and it appears that due to this limitation, I am getting this error. Can you please let me know how to resolve this issue?

**Comment by yangcheng** [comment]
i have same error when use python 3.11.6 on ubuntu 22.04. switch to python 3.8.18 get me pass this error. there are some other small issues need to fix, like gradio's latest version can;t be installed 

But for this particular error, use python 3.8 should help.

I hope the project can be more explicite about dependency versions.

**Comment by alireza18878** [comment]
> i have same error when use python 3.11.6 on ubuntu 22.04. switch to python 3.8.18 get me pass this error. there are some other small issues need to fix, like gradio's latest version can;t be installed
> 
> But for this particular error, use python 3.8 should help.
> 
> I hope the project can be more explicite about dependency versions.

Thanks, but in the instructions it indicates that the requirement is Python 3.8 or greater (Python>=3.8). And Python 3.11 is indeed newer than 3.8 (the version numbering in Python is a little different apparently). So shouldn't it work with Python 3.11 when it is newer than 3.8?

**Comment by alireza18878** [comment]
@

> i have same error when use python 3.11.6 on ubuntu 22.04. switch to python 3.8.18 get me pass this error. there are some other small issues need to fix, like gradio's latest version can;t be installed
> 
> But for this particular error, use python 3.8 should help.
> 
> I hope the project can be more explicite about dependency versions.

@yangcheng Thanks, this solved the issue.

**Comment by thekaranacharya** [comment]
Just tested this on Python v`3.10.14`. It works fine! I think this is the latest python version with which Inpaint-Anything can work.
