### ISSUE TITLE
imageio.mimread() has read over 256000000B of image data

### ISSUE THREAD

**Issue by SakuraMaiii** [geekyutao/Inpaint-Anything#136]
Traceback (most recent call last):
  File "E:\AI\Inpaint-Anything\remove_anything_video.py", line 357, in <module>
    all_frame = iio.mimread(video_raw_p)
  File "D:\AI\Miniconda\envs\inpaint\lib\site-packages\imageio\v2.py", line 455, in mimread
    raise RuntimeError(
RuntimeError: imageio.mimread() has read over 256000000B of image data.
Stopped to avoid memory problems. Use imageio.get_reader(), increase threshold, or memtest=False

i dont know why sir

**Comment by SakuraMaiii** [comment]
python remove_anything_video.py  --input_video in\Taylor.mp4 --coords_type key_in --point_coords 245 342 --point_labels 1 --dilate_kernel_size 15 --output_dir out --sam_model_type "vit_h" --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth --lama_config lama/configs/prediction/default.yaml --lama_ckpt ./pretrained_models/big-lama --tracker_ckpt vitb_384_mae_ce_32x4_ep300 --vi_ckpt ./pretrained_models/sttn.pth  --mask_idx 2 --fps 25

**Comment by cseconds** [comment]
i have the same question, but i fix this by modifing the code "all_frame = iio.mimread(video_raw_p)" to "all_frame = iio.mimread(video_raw_p, memset=False)";
 But after solving this problem, it still cannot run, i input 2s video, it comes an error : "torch.cuda.OutOfMemoryError: CUDA out of memory."  I dont know why 2s video meet this problem, my GPU has 40GB memory.
