### ISSUE TITLE
Detectron v2 is not installed

### ISSUE THREAD

**Issue by JXCrazy** [geekyutao/Inpaint-Anything#15]
When i run this code following: python remove_anything.py  --input_img ./example/remove-anything/dog.jpg --point_coords 200 450 --point_labels 1 --dilate_kernel_size 15 --output_dir ./results  --sam_model_type "vit_h" --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth --lama_config ./lama/configs/prediction/default.yaml --lama_ckpt ./pretrained_models/big-lama, there have:
![image](https://user-images.githubusercontent.com/72930251/233030432-949bf3eb-d1c4-4d74-8f89-6835aeac1baa.png)

i keep following as the Installation and usage instruation, but i can't know what happend to get the "Detectron v2 is not installed" error?

**Comment by JXCrazy** [comment]
> 

And what is the "Detectron v2"? Is it Mmdetection v2?

**Comment by geekyutao** [comment]
> When i run this code following: python remove_anything.py --input_img ./example/remove-anything/dog.jpg --point_coords 200 450 --point_labels 1 --dilate_kernel_size 15 --output_dir ./results --sam_model_type "vit_h" --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth --lama_config ./lama/configs/prediction/default.yaml --lama_ckpt ./pretrained_models/big-lama, there have: ![image](https://user-images.githubusercontent.com/72930251/233030432-949bf3eb-d1c4-4d74-8f89-6835aeac1baa.png)
> 
> i keep following as the Installation and usage instruation, but i can't know what happend to get the "Detectron v2 is not installed" error?

Just ignore it. Refer to this [issue](https://github.com/advimman/lama/issues/171).

**Comment by JXCrazy** [comment]
Yeah! 
I just ignore it, and then I can generate removed results. 
In addition, i have a question: 
                                             Can't I automatically select the picture and mark the coordinate points through the code? 
                                             I can only manually enter the coordinates to eliminate objects, because I tested it on my own data, and the effect is good or bad, and the generalization ability of this "Segment Anything Model (SAM)" is also limited. (Hahaha...)

**Comment by geekyutao** [comment]
> Yeah! I just ignore it, and then I can generate removed results. In addition, i have a question: Can't I automatically select the picture and mark the coordinate points through the code? I can only manually enter the coordinates to eliminate objects, because I tested it on my own data, and the effect is good or bad, and the generalization ability of this "Segment Anything Model (SAM)" is also limited. (Hahaha...)

Hi, that's exactly what we are working on. The demo website is coming soon. You can achieve it when it's released. Before that, you may need use [get_ponit_coor.py](https://github.com/geekyutao/Inpaint-Anything/blob/main/utils/get_ponit_coor.py) to get the coordinates.
SAM performs better when you give more positive/negative points, and we're considering the multi-click feature.

**Comment by geekyutao** [comment]
I close this issue as completed.

**Comment by block003** [comment]
![image](https://github.com/geekyutao/Inpaint-Anything/assets/126661122/50065c3a-bf62-4c97-8981-b87cdfacf665)
but i have no results，

**Comment by block003** [comment]
> ![图像](https://private-user-images.githubusercontent.com/126661122/329772579-50065c3a-bf62-4c97-8981-b87cdfacf665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjQ4NTAsIm5iZiI6MTcxNTQyNDU1MCwicGF0aCI6Ii8xMjY2NjExMjIvMzI5NzcyNTc5LTUwMDY1YzNhLWJmNjItNGM5Ny04OTgxLWI4N2NkZmFjZjY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxMDQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDcwMDVmMjk3OTg0ODY4ZjU4YTVkN2I2NjI3MzkxNGRiYWVlYTc0MjVjNGZiNTUxMzgzMTQ0NTJkYmI1ODhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q1YxPlv3UJqrSoEZ2yxPo26tUZuWDtJaRsLXQJfD0yI)但我没有结果，

I do  ，sry

**Comment by KevinkinBePositive** [comment]
![image](https://github.com/user-attachments/assets/bbeb38f5-3b8a-4f45-ad87-97414f1f9bea)
A link appeared, but it did not automatically redirect. After clicking, I found that the link could not be opened. How can I solve this problem?
