### ISSUE TITLE
Solve Prompt Matters

### ISSUE THREAD

**Issue by cjfghk5697** [geekyutao/Inpaint-Anything#16]
Hi, Thank you for the good paper and project. 
I saw the issue of prompts in the research paper. How about developing a model that logically explains complex sentences by dividing them, or using it like Visual ChatGPT?
Specifically, it can solve by decomposing like [Visual ChatGPT](https://arxiv.org/abs/2303.04671). This method of breaking complex sentences into shorter sentences and processing them in order.

![image](https://user-images.githubusercontent.com/80466735/233059970-b6c5f4a9-236c-4ca6-8934-ab5b753a7f92.png)

- The image is contained in Visual ChatGPT paper 3.1, Prompt Managing of System Principles _M(P)_

**Comment by geekyutao** [comment]
> Visual ChatGPT

Not sure if I understand correctly. Did you mean decomposing a generation task to several sub-tasks?

**Comment by cjfghk5697** [comment]
Yes, AIGC model cannot tend to be less user-friendly, because is complex and longer text-prompt. 
To be more user-friendly, text-prompt by decomposing into subproblems before text-prompt inputs to AIGC model. 
After that, AIGC model processes divided tasks sequentially.
For example, “generate a red flower conditioned on the predicted depth of this image and then make it like a cartoon ” can divide into "generate red flower on the predicted" and then "make it like a cartoon".

However, it requires more computing.
Since I am an undergraduate, there are many shortcomings in my proposal.
I'm so sorry about that.

**Comment by geekyutao** [comment]
> 

It's very insightful, thank you! In that way, AIGC model can be more accurate and controllable.

**Comment by cjfghk5697** [comment]
Thanks you for answer.
This issue cannot help you, but pray you solve this problem!
