### ISSUE TITLE
Separate all segments?

### ISSUE THREAD

**Issue by Zaniyar** [geekyutao/Inpaint-Anything#18]
This is not an error, more a question; **is it somehow possible to segment any object in the image + fill the hole and save the segmentations as separate pngs?**

**Comment by geekyutao** [comment]
> 

Yes, it's possible. You can refer to the "Everything" feature in [SAM demo website](https://segment-anything.com/demo#).

**Comment by geekyutao** [comment]
> This is not an error, more a question; **is it somehow possible to segment any object in the image + fill the hole and save the segmentations as separate pngs?**

Yes, it's possible. You can refer to the "Everything" feature on [SAM demo website](https://segment-anything.com/demo#).
