### ISSUE TITLE
What are the difference/contribution of this project compared to existings?

### ISSUE THREAD

**Issue by hello451** [geekyutao/Inpaint-Anything#2]
It seemed that Grounding SAM and many other projects can do better? Inpainting, editing and so on.

**Comment by hello451** [comment]
It seemed that you did not answer his follow-up question.

**Comment by LinghaoChan** [comment]
> It seemed that Grounding SAM and many other projects can do better? Inpainting, editing and so on.

Yep. Actually, Grounding SAM has supported the inpainting function. As for the click function, it is just an engineering implementation with several python codes.

**Comment by LinghaoChan** [comment]
Check out the discussion from Twitter: https://twitter.com/jw2yang4ai/status/1647782062517276675.
