### ISSUE TITLE
Question: Remove Anything uses only Lama

### ISSUE THREAD

**Issue by Markus-Pobitzer** [geekyutao/Inpaint-Anything#20]
Good Morning

Thank you for your contribution. I was wondering why you used only Lama for "Remove Anything". Did you find it better suited than Stable Diffusion inpainting?

**Comment by geekyutao** [comment]
> Good Morning
> 
> Thank you for your contribution. I was wondering why you used only Lama for "Remove Anything". Did you find it better suited than Stable Diffusion inpainting?

Hi Markus, Remove Anything can use any inpainting models, LaMa, Stable Diffusion (SD), etc. But we chose LaMa for several reasons: 1) LaMa supports any aspect ratio while SD not; 2) LaMa supports 2K resolution while SD not; and 3) SD inpainting requires inputing proper text prompts to recover background, not as convenient as LaMa.
