### ISSUE TITLE
请问哪里可以下载big-lama模型，官方链接打不来

### ISSUE THREAD

**Issue by Lee-Naoer** [geekyutao/Inpaint-Anything#22]

**Comment by qlz58793** [comment]
您好，也许您可以试下这个链接里的方法~
https://github.com/advimman/lama/issues/157

**Comment by word-to-world** [comment]
https://huggingface.co/camenduru/big-lama/tree/main/big-lama

**Comment by Lee-Naoer** [comment]
thank you so much! i find it.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [geekyutao/Inpaint-Anything] 请问哪里可以下载big-lama模型，官方链接打不来 (Issue #22)




 
https://huggingface.co/camenduru/big-lama/tree/main/big-lama

**Comment by geekyutao** [comment]
I close it as completed.
