### ISSUE TITLE
Do you have simple interface to use these? 

### ISSUE THREAD

**Issue by FurkanGozukara** [geekyutao/Inpaint-Anything#27]
I would like to make a tutorial video on my channel [SECourses ](https://www.youtube.com/SECourses )  but I don't see gradio interface or such as in your examples

If you don't have can you release the interface you used to generate those examples images you put in main page?

That shows masked / segmented content after clicking

**Comment by geekyutao** [comment]
> I would like to make a tutorial video on my channel [SECourses ](https://www.youtube.com/SECourses) but I don't see gradio interface or such as in your examples
> 
> If you don't have can you release the interface you used to generate those examples images you put in main page?
> 
> That shows masked / segmented content after clicking

Thanks for your interest! The interface is coming soon, may be finished this week. You can also refer to  [GIF](https://github.com/geekyutao/Inpaint-Anything/tree/main/example/GIF) for some GIF demos.

**Comment by Sanster** [comment]
@FurkanGozukara hi, perhaps you would be interested in my project  [Lama Cleaner](https://github.com/Sanster/lama-cleaner) which integrates multiple SOTA inpainting models, including SAM+Stable Diffusion

Demo video for using SAM+Stable Diffusion in Lama Cleaner

https://user-images.githubusercontent.com/3998421/233762880-bbb888d8-5f52-4b08-bbe4-e9df9351120d.mp4

Demo video for using SAM+[LaMa](https://github.com/advimman/lama) in Lama Cleaner

https://user-images.githubusercontent.com/3998421/233762926-5d1b3e0f-7d51-4d40-865b-6fb98869ecfd.mp4

**Comment by continue-revolution** [comment]
If you use stable diffusion webui, use https://github.com/continue-revolution/sd-webui-segment-anything, check https://github.com/continue-revolution/sd-webui-segment-anything#how-to-use and https://github.com/continue-revolution/sd-webui-segment-anything/issues/60 for how to use

**Comment by FurkanGozukara** [comment]
> If you use stable diffusion webui, use https://github.com/continue-revolution/sd-webui-segment-anything, check https://github.com/continue-revolution/sd-webui-segment-anything#how-to-use and [continue-revolution/sd-webui-segment-anything#60](https://github.com/continue-revolution/sd-webui-segment-anything/issues/60) for how to use

thanks useful
