### ISSUE TITLE
Try Inpaint Anything in A1111 Stable Diffusion WebUI

### ISSUE THREAD

**Issue by continue-revolution** [geekyutao/Inpaint-Anything#29]
An [issue](https://github.com/continue-revolution/sd-webui-segment-anything/issues/58) inside my extension redirected me here. Many people might be excited about this work, but have no good user interface. If you use A1111 SD-WebUI, [my SAM extension](https://github.com/continue-revolution/sd-webui-segment-anything) + [Mikubill ControlNet extension](https://github.com/Mikubill/sd-webui-controlnet) are all you need to try inpaint-anything inside a good and easy-to-use UI. Check [README](https://github.com/continue-revolution/sd-webui-segment-anything#how-to-use) and [this tutorial](https://github.com/continue-revolution/sd-webui-segment-anything/issues/60) for how to use. You do not need to download whatever huge annoying general-purposed inpaint model. A base model + lllyasviel ControlNet inpainting model + SAM are all you need.

**Comment by geekyutao** [comment]
> An [issue](https://github.com/continue-revolution/sd-webui-segment-anything/issues/58) inside my extension redirected me here. Many people might be excited about this work, but have no good user interface. If you use A1111 SD-WebUI, [my SAM extension](https://github.com/continue-revolution/sd-webui-segment-anything) + [Mikubill ControlNet extension](https://github.com/Mikubill/sd-webui-controlnet) are all you need to try inpaint-anything inside a good and easy-to-use UI. Check [README](https://github.com/continue-revolution/sd-webui-segment-anything#how-to-use) and [this tutorial](https://github.com/continue-revolution/sd-webui-segment-anything/issues/60) for how to use. You do not need to download whatever huge annoying general-purposed inpaint model. A base model + lllyasviel ControlNet inpainting model + SAM are all you need.

Hi, we are happy to see more and more works using our concept of "Inpaint Anything" as this project is completely open source. We tried your extensions, and they are awesome. But perhaps you have noticed that they are not that easy-to-use/understand. At least, not everyone can pick them up in one or two minutes. Simplicity and convenience are values. This is why iPhone's "Notes" app has always been one of the most polupar notebook apps. Rome wasn't built in a day. Currently, we have released a [website](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything) where users can upload their images to try Inpaint Anything. But we will make this project more powerful and user-friendly. Thanks.

**Comment by abczhaoling** [comment]
hi
