### ISSUE TITLE
如何自動移除物件?

### ISSUE THREAD

**Issue by stphtan94117** [geekyutao/Inpaint-Anything#3]
你好，謝謝你們偉大的作品
想請問，如果想要自動消除某個物件，例如移除車子
可以下一個指令，例如 remove car 就把所有車子都移除掉

目前你的版本是手動點擊，不知道能否做到自動化的方式
謝謝

**Comment by geekyutao** [comment]
> 你好，謝謝你們偉大的作品 想請問，如果想要自動消除某個物件，例如移除車子 可以下一個指令，例如 remove car 就把所有車子都移除掉
> 
> 目前你的版本是手動點擊，不知道能否做到自動化的方式 謝謝

谢谢~ 我们目前只做交互式的（即手动点击），如果想要实现你说的功能，需要像GroundedSAM那样在前端接一个Grounding model。

**Comment by stphtan94117** [comment]
請問短期間 有機會實現上述功能嗎 使用者下命令移除物件 就會自動移除該照片的物件(eg: car person...)
同上 是否支援多物件移除

**Comment by stphtan94117** [comment]
@geekyutao 自己是新手 還不會串接其他model進去，但還是希望你們未來有機會 能新增此功能，至於多物件移除 可以緩一緩
總之謝謝你
