### ISSUE TITLE
How can you crop the painted/replaced area?

### ISSUE THREAD

**Issue by antoinemacia** [geekyutao/Inpaint-Anything#30]
Hello! Great work this lib is amazing so far!

I am wondering how can we crop the area segmented by SAM, inpaint it with SD and expose that as an image on its own; The output Im trying to get is a mask of a point selection inpainted and everything else on the image as transparent or black

Would anyone know how to do that? Maybe Im missing something and SAM already exposes the mask as black/white images? I feel like everything is there to do that and its just a matter of piping things together properly, any help would be appreciated!

**Comment by geekyutao** [comment]
Yes, SAM outputs binary masks when performing segmentation. You can try it on our [website](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything).

**Comment by antoinemacia** [comment]
Thanks @geekyutao!
