### ISSUE TITLE
Run remove_anything.py error

### ISSUE THREAD

**Issue by TianSong1991** [geekyutao/Inpaint-Anything#34]
When I run your demo remove_anything.py, it returns error that 

> ImportError: cannot import name 'SamPredictor' from 'segment_anything' (unknown location)
This error is in **_from segment_anything import SamPredictor, sam_model_registry_**

I find the SamPredictor class is in predictor.py not segment_anything.py. Does anyone has this problem?

My run order is 

> python ./remove_anything.py   --input_img ./example/remove-anything/dog.jpg    --point_coords 200 450    --point_labels 1  --dilate_kernel_size 15    --output_dir ./results     --sam_model_type "vit_h"     --sam_ckpt ./sam_vit_h_4b8939.pth    --lama_config ./lama/configs/prediction/default.yaml     --lama_ckpt ./pretrained_models/big-lama

**Comment by TianSong1991** [comment]
Sorry, I use win10 and I only 

> pip install -r lama_requirements_windows.txt

I lost to use the follow order:

> python -m pip install torch torchvision torchaudio
> python -m pip install -e segment_anything
> python -m pip install -r lama/requirements.txt 

This problem is solved. But it returns another error 

> Detectron v2 is not installed

**Comment by RysonFeng** [comment]
'Detectron v2 is not installed' is not an error. It is an import warning in the original lama code. Just ignore it.

**Comment by TianSong1991** [comment]
I have solved the problem to install Detectron v2.Thanks all.
