### ISSUE TITLE
Run app.py Error：cannot import name 'build_lama_model' from 'lama_inpaint'

### ISSUE THREAD

**Issue by distort5871** [geekyutao/Inpaint-Anything#35]
# DESC
hi, i am so surprised by your latest feature, the local web ui, so i quickly run the app.py for a test, however i get an error like this: cannot import name 'build_lama_model' from 'lama_inpaint'
**please help me solve the problem, or give me more information about this, thanks!**
# COMMAND
```bash
python app.py \
>       --lama_config  /home/lcc/github.com/Inpaint-Anything/pretrained_models/big-lama/config.yaml \
>       --lama_ckpt  /home/lcc/github.com/Inpaint-Anything/pretrained_models/big-lama/models/best.ckpt \
>       --sam_ckpt /home/lcc/github.com/Inpaint-Anything/pretrained_models/sam_vit_h_4b8939.pth
```
# ERROR
```bash
Detectron v2 is not installed
Traceback (most recent call last):
  File "/home/lcc/github.com/Inpaint-Anything/app/app.py", line 13, in <module>
    from lama_inpaint import inpaint_img_with_lama, build_lama_model, inpaint_img_with_builded_lama
ImportError: cannot import name 'build_lama_model' from 'lama_inpaint' (/home/lcc/github.com/Inpaint-Anything/lama_inpaint.py)
```
# MY ENV
```bash
centos7
GCC9.5
python3.9
cuda 11.3
torch 1.12.1
```

**Comment by geekyutao** [comment]
Hi, we updated the code and instruction. Please use the latest version. It should work. I just tested it.

**Comment by zhdwwf** [comment]
I have same issue with latest version

**Comment by geekyutao** [comment]
> I have same issue with latest version

Did you follow the latest instruction to run the demo web?

**Comment by zhdwwf** [comment]
I found my mistake, I did't enter the app folder
`
python ./app/app.py
`
use this code not work,need to execute in app folder

**Comment by distort5871** [comment]
> @distort5871 In your context, kindly try this:
> 
> ```
> python app.py \
>        --lama_config ./lama/configs/prediction/default.yaml \
>        --lama_ckpt  /home/lcc/github.com/Inpaint-Anything/pretrained_models/big-lama \
>        --sam_ckpt /home/lcc/github.com/Inpaint-Anything/pretrained_models/sam_vit_h_4b8939.pth
> ```

thanks so much, it works for me.
