### ISSUE TITLE
Python complains when I attempt to install segment anything

### ISSUE THREAD

**Issue by pshaddock** [geekyutao/Inpaint-Anything#4]
Here is the error message:

ERROR: segment_anything is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

I must be doing something wrong. Please tell me what it is. Thank you.

**Comment by geekyutao** [comment]
> 

Hi, try to install SAM under the root directory of the repository.
