### ISSUE TITLE
 No such file or directory: 'big-lama\\config.yaml'

### ISSUE THREAD

**Issue by Cassiatora** [geekyutao/Inpaint-Anything#5]

**Comment by geekyutao** [comment]
Hi, check out here: https://disk.yandex.ru/d/ouP6l8VJ0HpMZg

**Comment by zhhezhhe** [comment]
could not download https://disk.yandex.ru/d/ouP6l8VJ0HpMZg

**Comment by Provemj** [comment]
Nothing found
There is a typo in the link, or the owner has deleted the files or blocked access to them.
The links says so
