### ISSUE TITLE
Huggingface Spaces showing runtime error

### ISSUE THREAD

**Issue by skulshreshtha** [geekyutao/Inpaint-Anything#52]
[Huggingface space](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything) for this project shows `Runtime error`

<img width="1286" alt="Screenshot 2023-05-01 at 10 48 37" src="https://user-images.githubusercontent.com/51631078/235431005-d8f5c77d-1b4c-49ab-9f8a-e0325659d5ac.png">

**Comment by geekyutao** [comment]
May I ask what the size of your image? Seems Hugging Face server cannot handle this image due to memory limit. I recommend you to run web UI locally. Kindly follow app/README.md for the instruction.

**Comment by skulshreshtha** [comment]
I haven't gotten to uploading any images yet. The app doesn't load in the space at all.

**Comment by geekyutao** [comment]
> I haven't gotten to uploading any images yet. The app doesn't load in the space at all. However, I am able to run it locally. Thanks!

I just noticed that the web is broken. We are fixing it. Pls check the web a few hours later.

**Comment by geekyutao** [comment]
@skulshreshtha bug fixed.

**Comment by skulshreshtha** [comment]
Thank you @geekyutao. I was trying to fix myself as well. Is there a commit related to this bug fix that I can see to understand what was the issue?

**Comment by geekyutao** [comment]
> Thank you @geekyutao. I was trying to fix myself as well. Is there a commit related to this bug fix that I can see to understand what was the issue?

Honestly, we haven't located the cause. We just re-builded the space, and the error disappeared. The commits can be found in [cdd0075b767309f1dcba7bfd5e80eced96922fb4](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything/commit/cdd0075b767309f1dcba7bfd5e80eced96922fb4) and [6ef35b426740f60809b8eff620b7d3f337f4d569](https://huggingface.co/spaces/InpaintAI/Inpaint-Anything/commit/6ef35b426740f60809b8eff620b7d3f337f4d569).
