### ISSUE TITLE
Errors when run the Remove Anything Video

### ISSUE THREAD

**Issue by Zixuan-Xu-GodVision** [geekyutao/Inpaint-Anything#60]
hi， when I run the remove_anything_video.py, comes the errors as following:

(Inpaint_Anything) E:\Sydney University\CVProject\Project\Inpaint_Anything\Inpaint-Anything-main>python remove_anything_video.py --input_video ./example/video/paragliding/original_video.mp4 --coords_type key_in --point_coords 652 162 --point_labels 1 --dilate_kernel_size 15 --output_dir ./results --sam_model_type "vit_h" --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth --lama_config lama/configs/prediction/default.yaml --lama_ckpt ./pretrained_models/big-lama --tracker_ckpt vitb_384_mae_ce_32x4_ep300 --vi_ckpt ./pretrained_models/sttn.pth --mask_idx 2 --fps 25
Detectron v2 is not installed
Traceback (most recent call last):
  File "E:\Sydney University\CVProject\Project\Inpaint_Anything\Inpaint-Anything-main\remove_anything_video.py", line 384, in <module>
    model = RemoveAnythingVideo(args)
  File "E:\Sydney University\CVProject\Project\Inpaint_Anything\Inpaint-Anything-main\remove_anything_video.py", line 117, in __init__
    self.segmentor = self.build_segmentor(
  File "E:\Sydney University\CVProject\Project\Inpaint_Anything\Inpaint-Anything-main\remove_anything_video.py", line 131, in build_segmentor
    return build_sam_model(**kwargs)
  File "E:\Sydney University\CVProject\Project\Inpaint_Anything\Inpaint-Anything-main\sam_segment.py", line 39, in build_sam_model
    sam.to(device=device)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "D:\Anaconda\envs\Inpaint_Anything\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I think the problem is the Cuda version is not compatible with Torch version, but when I download the new version of Torch, comes a lot of other problems, even the other function remove,fill, and replace can not be used(it can be run correctly before), so do you know how to solve this problem?and do you have any recommend suitable cuda version?

**Comment by Zixuan-Xu-GodVision** [comment]
The installation requires commond is :python -m pip install torch torchvision torchaudio， this code install the pytorch without the cuda, but somewhere in the remove_anything_video.py it seems using the cuda, so here comes the problem I guss, so maybe should update the requires or delete the cuda parts.

**Comment by Zixuan-Xu-GodVision** [comment]
另一个问题是remove anything video提供的checkpoints文件格式似乎不对，我通过您在Usage上的链接下载并且解压后，尽管他的名称是OSTrack_ep0300.pth，但是实际的格式仍然是文件夹格式而不是.pth格式，所以导致没法调用，希望您能解答我的问题

**Comment by geekyutao** [comment]
> 另一个问题是remove anything video提供的checkpoints文件格式似乎不对，我通过您在Usage上的链接下载并且解压后，尽管他的名称是OSTrack_ep0300.pth，但是实际的格式仍然是文件夹格式而不是.pth格式，所以导致没法调用，希望您能解答我的问题

You can rename it or re-download from [here](https://drive.google.com/drive/folders/1SERTIfS7JYyOOmXWujAva4CDQf-W7fjv).

**Comment by wheynelau** [comment]
Have you tried using conda instead? I find that installation has lesser issues when using conda. 
Here is the command, you will need to create an env first however. 
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

**Comment by Zixuan-Xu-GodVision** [comment]
> @Zixuan-Xu-GodVision Have you tried using conda instead? I find that installation has lesser issues when using conda. Here is the command, you will need to create an env first however.
> 
> ```
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> # other commands
> # pip install ... 
> ```

Yeah, I tried, but after using conda to install, something else still wrong, so I think simply way to run it directly change the cuda to cpu

**Comment by Zixuan-Xu-GodVision** [comment]
> > The installation requires commond is :python -m pip install torch torchvision torchaudio， this code install the pytorch without the cuda, but somewhere in the remove_anything_video.py it seems using the cuda, so here comes the problem I guss, so maybe should update the requires or delete the cuda parts.
> 
> Firstly, change the device to "cpu" and check out if it runs normally.
> 
> https://github.com/geekyutao/Inpaint-Anything/blob/a68eff249a07ea081e584ad262cbfbba8dc2a196/remove_anything_video.py#L334
> 
> 
> You then need configure torch and cuda according to your device (e.g., GPU type). I'm afraid I can't help you without enough context.

Thanks for replying, after chnage to "cpu", it can not run normally, 
but I figure it out , using conda to install the pytorch again.

**Comment by ert485** [comment]
I was having this problem too while trying to run with CPU only. The problem is that `remove_anything_video.py` calls functions like `build_sam_model` in `sam_segment.py` (and also in `sttn_video_inpaint.py`) without specifying the `device`. It's usually an optional parameter that defaults to "cuda". I tried fixing that, but also it seems like `pytracking/lib/test/tracker/ostrack.py` also assumes you have cuda instead of cpu and I couldn't figure out quickly how to switch it
