### ISSUE TITLE
How to get the video coordinate

### ISSUE THREAD

**Issue by Zixuan-Xu-GodVision** [geekyutao/Inpaint-Anything#61]
Hi， I got a problem during run the remove anything video.
Remove Anyting Video can only run by --coords_type key_in not click, so I use CV2 to get the first frame and get the coordinate of the thing I want to remove, but after run the code, the coordinate was totally different with what I got by the CV2 script，so how do you get the video coordinate?

**Comment by Zixuan-Xu-GodVision** [comment]
Another thing is it seems the there are certain requirements for the definition of the video, if the definition is too high, it will not be recognized normally, so I want to ask what are the specific requirements for the video，like at most 4K or others?

**Comment by geekyutao** [comment]
> Another thing is it seems the there are certain requirements for the definition of the video, if the definition is too high, it will not be recognized normally, so I want to ask what are the specific requirements for the video，like at most 4K or others?

Kindly set `--coords_type` to `click`, then you can click to input a point.

**Comment by geekyutao** [comment]
> Hi， I got a problem during run the remove anything video. Remove Anyting Video can only run by --coords_type key_in not click, so I use CV2 to get the first frame and get the coordinate of the thing I want to remove, but after run the code, the coordinate was totally different with what I got by the CV2 script，so how do you get the video coordinate?

I updated the code of remove_anything_video. It now supports for clicking to input a point. Kindly set `--coords_type` to `click`.

**Comment by geekyutao** [comment]
> Another thing is it seems the there are certain requirements for the definition of the video, if the definition is too high, it will not be recognized normally, so I want to ask what are the specific requirements for the video，like at most 4K or others?

4K requires huge computation resouces. It should work if the memory is sufficient. But the video inpainting model we used STTN seems to perform a resize operation which may downscale the video.

**Comment by Zixuan-Xu-GodVision** [comment]
Got it, thanks for answer!
