### ISSUE TITLE
Does Inpaint-Anything not support MacBook Pro with Intel CPU?

### ISSUE THREAD

**Issue by Pengree** [geekyutao/Inpaint-Anything#7]
When I run the command:
`python3 -m pip install -r lama/requirements.txt`
the system displays an error message saying that 
`the clang compiler does not support '-march=native'.` 

Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.

[error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)

**Comment by geekyutao** [comment]
> When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> 
> Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> 
> [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)

Not sure if it supports MacOS. But we are trying to achieve it.

**Comment by geekyutao** [comment]
> When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> 
> Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> 
> [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)

Just tested it. It works fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. But you may need install additional packages. You can refer to my test log where I installed the repo from scratch and ran it successfully.
[macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)

**Comment by Pengree** [comment]
> > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> 
> @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> 
> [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)

 I wanted to express my gratitude for your prompt response and assistance with my recent inquiry regarding the installation of TensorFlow on my Macbook Pro.

I followed your advice and installed tf-nightly independently. Then, I went ahead and installed the other necessary modules step by step according to your installation log. I am happy to report that I was able to successfully install everything and run it without any issues.

Thanks again.

> > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> 
> @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> 
> [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)

@geekyutao 



> > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> 
> @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> 
> [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)

 I wanted to express my gratitude for your prompt response and assistance with my recent inquiry regarding the installation of TensorFlow on my Macbook Pro.

I followed your advice and installed tf-nightly independently. Then, I went ahead and installed the other necessary modules step by step according to your installation log. I am happy to report that I was able to successfully install everything and run it without any issues.

Thanks again.

**Comment by geekyutao** [comment]
> > > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> > 
> > 
> > @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> > [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)
> 
> I wanted to express my gratitude for your prompt response and assistance with my recent inquiry regarding the installation of TensorFlow on my Macbook Pro.
> 
> I followed your advice and installed tf-nightly independently. Then, I went ahead and installed the other necessary modules step by step according to your installation log. I am happy to report that I was able to successfully install everything and run it without any issues.
> 
> Thanks again.
> 
> > > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> > 
> > 
> > @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> > [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)
> 
> @geekyutao
> 
> > > When I run the command: `python3 -m pip install -r lama/requirements.txt` the system displays an error message saying that `the clang compiler does not support '-march=native'.`
> > > Does Inpaint-Anything not support MacBook Pro with Intel CPU? My MacBook Pro CPU is intel Core i5 Quad 2GHz, MacOS version is 13.1.
> > > [error.log](https://github.com/geekyutao/Inpaint-Anything/files/11264332/error.log)
> > 
> > 
> > @Pengree I just tested it. It worked fine on my M2 Macbook Air with 13.3.1 (22E261) version of MacOS. You can refer to my test log where I installed the repo from scratch and ran it successfully. You may need change installing tensorflow to tf-nightly.
> > [macos_test.log](https://github.com/geekyutao/Inpaint-Anything/files/11268426/macos_test.log)
> 
> I wanted to express my gratitude for your prompt response and assistance with my recent inquiry regarding the installation of TensorFlow on my Macbook Pro.
> 
> I followed your advice and installed tf-nightly independently. Then, I went ahead and installed the other necessary modules step by step according to your installation log. I am happy to report that I was able to successfully install everything and run it without any issues.
> 
> Thanks again.

You're welcome. Feel free to reach out me if there is any issue.
