### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by pshaddock** [geekyutao/Inpaint-Anything#8]
I still have the same problem with the installation of the software. Tried what you suggested. Same error:

D:\Inpaint-Anything>python -m pip install -e segment_anything
Defaulting to user installation because normal site-packages is not writeable
ERROR: segment_anything is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

D:\Inpaint-Anything>

**Comment by geekyutao** [comment]
> I still have the same problem with the installation of the software. Tried what you suggested. Same error:
> 
> D:\Inpaint-Anything>python -m pip install -e segment_anything Defaulting to user installation because normal site-packages is not writeable ERROR: segment_anything is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
> 
> D:\Inpaint-Anything>

I just realized that you are using Windows system. Can you try to install a WSL? Then you can install and run the repo smoothly.

**Comment by geekyutao** [comment]
Maybe you can contact @zhaofangtao from this [issue](https://github.com/geekyutao/Inpaint-Anything/issues/13) where he/she installed the repo in Windows successfully.

**Comment by zhaofangtao** [comment]
可能是用户操作目录权限不足，可以右键点“已管理员身份运行”打开你的编辑器，再在terminal试一下

**Comment by dan-willett** [comment]
Besides needing to run your terminal as administrator ( either PowerShell or Cmd )

The answer to this is that the installation instructions leave out 3 key steps:

Step 1: go into the folder where you want to put the folder for Inpaint-Anything
Step 2: clone this repository using this command: 

```sh
git clone https://github.com/geekyutao/Inpaint-Anything
```

Step 3: change into the Inpaint-Anything folder:

```sh
cd Inpaint-Anything
```

**Comment by RysonFeng** [comment]
Besides the above answers, we recommend to install minicoda for virtual environment managements on windows.
You can refer to the answers of issue [#17](https://github.com/geekyutao/Inpaint-Anything/issues/17).
